### ISSUE TITLE
Supply arbitrary list of supporting images

### ISSUE THREAD

**Issue by shanejansen** [shanejansen/touchstone#19]
Some services need supporting images which do no include mocks. Add ability to specify a list of "supporting" Docker images to spin up when Touchstone is started

**Comment by ScottFreeCode** [comment]
Is there anything specifically that would be different for this vs using a combination of #18 and #21 to add them as services without tests?

**Comment by shanejansen** [comment]
@ScottFreeCode I like that idea. You'll also get the built in Docker health check by defining it as a service
