### ISSUE TITLE
ANY does not match numbers?

### ISSUE THREAD

**Issue by ScottFreeCode** [shanejansen/touchstone#22]
Exactly what it says on the tin; I've got a payload json comparison where validation.ANY works for strings but for numbers (integers, specifically, not sure if that's a different type) I have to hardcode the number in order to pass.

The code doesn't have any obvious (to me) problems that would cause this…

When looking at this be aware of #23

**Comment by shanejansen** [comment]
The root cause of this issue was related to arrays containing validation.ANY

**Comment by ScottFreeCode** [comment]
Ah, I think you're right; I hadn't realized the string cases were top-level but the number cases were in dicts in lists. I naively saw they're both in dicts and assumed they'd be compared the same except for something about the fields themselves.
