### ISSUE TITLE
Service logs do not cover immediate startup failures

### ISSUE THREAD

**Issue by ScottFreeCode** [shanejansen/touchstone#36]
Usually when a service fails to pass the healthcheck, `--log-services` provides useful info. However, sometimes the log file is empty and to see its output I have to catch the container with a Docker attach command in the fleeting window during which it is live. It seems as though Touchstone connects to the container after the initial docker run command to get the logs. I would expect it to direct the container output to a file as part of the initial container run/start command, guaranteeing all output is logged.

**Comment by shanejansen** [comment]
Touchstone does run containers with the `--rm` flag, so you're right the container could be removed before Touchstone has a change to get logs if a health check fails.

During shutdown, Touchstone will clean up images that it produced (like supplying a Dockerfile in `touchstone.yml`)

**Comment by ScottFreeCode** [comment]
I have opened two PRs with different possible fixes, with different pros and cons. #42 and #43
